project_id = "jfxtpupdgljcxvyrgxag"

[functions.extract-profile]
verify_jwt = true

[functions.generate-recommendations]
verify_jwt = true

[functions.send-results-email]
verify_jwt = true

[functions.create-payment]
verify_jwt = false

[functions.check-payment]
verify_jwt = false
